with open('exemplo.txt' , 'a') as arquivo:
    conteudo = arquivo.write('Ano de 1950: O início\n'
'Um dos primeiros carros usados em corridas. Propriedade da compania Alfa Romeo, usado na temporada de 1950 em Silverstone na Inglaterra.\n'
'Seguindo os dirigentes do automobilismo, a FIA (Federação Internacional de Automobilismo) anunciou a prova inaugural do campeonato mundial de F-1, em um sábado, 13 de maio de 1950 no Circuito de Silverstone, na Inglaterra, para não coincidir com um culto religioso local.\n'
'O campeonato anunciado compreendia 6 GPs a serem disputados na Europa: Inglaterra, Mônaco, Suíça, Bélgica, França e Itália, e seria ainda adicionado o resultado das 500 Milhas de Indianápolis, tornando, dessa maneira, um campeonato "mundial" (apesar do fato de que os carros, equipes e pilotos que competiam nos EUA serem completamente diferentes dos da Europa).\n'
'Devido às dificuldades do pós-guerra, os carros eram todos do pré-guerra. Permitiu-se a participação de carros com motores superpressurizados até 1,5 litro ou com motores aspirados de 4,5 litros. A confirmação da presença da Alfa Romeo foi determinante para o momento. Sua participação com as Alfettas, dominantes na época, trouxe prestígio para o campeonato. Confirmaram presença a Ferrari (mas os carros não ficaram prontos para a prova inaugural), Maserati, algumas "Voiturettes" ERA e carros esportivos modificados, como os Talbots.\n'
'Seriam descartados os 3 piores resultados das 7 corridas disputadas. A pontuação era assim dividida: 8 pontos para o primeiro colocado; 6 para o segundo; 4 para o terceiro; 3 para o quarto; 2 para o quinto colocado e um ponto para o piloto que marcasse a volta mais rápida da prova.\n'
'A prova inaugural em Silverstone contou com um público de 100.000 pessoas estimadas, além da presença do Rei George VI, a Rainha Elizabeth e a princesa Margareth.\n'
'Após o domínio nos dois primeiros anos das Alfettas e as antigas voiturettes, a Ferrari apresenta um carro vencedor com motor de 4,5 litros e domina completamente os anos de 1952 e 1953, dando a Alberto Ascari o título de bicampeão. Neste momento, a Alfa, que competia ainda com as Alfettas (projeto do pré-guerra) não tinha recursos financeiros para investir no desenvolvimento de um novo projeto e decide abandonar a categoria.\n'
'Em 1954, a Mercedes-Benz retorna ao esporte com um carro perfeito que deu a Juan Manuel Fangio mais 2 títulos, tornando-se tricampeão mundial. Os carros são menores, com motores de 2,5 litros. Ao final de 1955, a Mercedes abandona as competições em razão da tragédia de Le Mans ocorrida naquele ano, quando mais de 80 espectadores morreram quando a Mercedes de Pierre Levegh projetou-se sobre a multidão. Neste momento, a Ferrari contrata Fangio, que conquista o quarto título na F-1. Em 1957, ele conquista seu quinto (e último) título pela Maserati.\n'
'Em 1955, a Vanwall, primeira equipe inglesa de F-1, apresenta um carro originalmente concebido para a Fórmula 2 de 2,0 litros, porém equipado com freios a disco e injeção de combustível. Nesse mesmo ano a Cooper inova com o 1o carro com motor traseiro, e mostrava como seria o futuro dos carros da F1. Em 1956, a Vanwall apresenta o motor de 2,5 litros e um novo chassi concebido por Colin Chapman, que nesta época desenvolvia carros esporte para a Lotus. Após algumas modificações introduzidas na suspensão por Chapman e a contratação de um especialista em carrocerias, Frank Costin, o carro da Vanwall tornou-se extremamente competitivo. Para brigar pelo campeonato foram contratados 2 excelentes pilotos: Stirling Moss e Tony Brooks. Assim, a Vanwall se tornou a primeira equipe campeã de construtores em 1958.\n'
'Em 1958, a Cooper apresenta um pequeno carro (baseado nos modelos da Fórmula 3 de 500cc) com motor de fabricação própria, montado na parte traseira, com um acentuado índice de avanço técnico comparado aos carros da época. Este carro marcou os modelos da década que se iniciava já sendo campeão de construtores e de pilotos, com o australiano Jack Brabham, em 1959 e 1960.\n'
                             'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n')
    print(conteudo)